services:
  backend:
    build: ./backend/
    command: sh -c "alembic upgrade head && python seed_db.py && python main.py"
    ports:
      - 8000:8000
    volumes:
      # - ./backend/src/vehicle/:/app/src/vehicle/
      - photo_storage:/app/src/vehicle/photos/cars
    env_file:
      - ./backend/.env
    depends_on:
      - db
    restart: on-failure

  
  db:
    image: postgres:16
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - 5432:5432
    volumes:
      - vehicle_db:/var/lib/postgresql/data
  
  frontend:
    build: ./frontend
    depends_on:
      - backend
    ports:
      - 8080:8080
    volumes:
      - ./frontend/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - photo_storage:/app/photo
    restart: always
  
  # bot:
  #   build: ./bot
  #   command: python -m bot.main
  #   env_file:
  #     - ./bot/.env
  #   depends_on:
  #     - db
  #   volumes:
  #     - ./bot/logs:/app/logs
  #   restart: on-failure

volumes:
  vehicle_db:
  photo_storage: