services:
  # nginx:
  #   image: nginx:stable-alpine
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
  #     - photo_storage:/app/photo
  #   depends_on:
  #     - backend
  #     - frontend
  #   restart: always

  backend:
    build: ./backend/
    command: sh -c "alembic upgrade head && python seed_db.py && python main.py"
    ports:
      - 8000:8000
    volumes:
      - ./backend/src/vehicle/:/app/src/vehicle/
      - photo_storage:/app/src/vehicle/photos/cars
    env_file:
      - .env
    depends_on:
      db:
       condition: service_healthy
    restart: on-failure

  
  db:
    image: postgres:16
    restart: always
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}"]
      interval: 1s
      timeout: 5s
      retries: 10
    env_file:
      - .env
    volumes:
      - vehicle_db:/var/lib/postgres/data
  
  frontend:
    build: ./frontend
    depends_on:
      - backend
    ports:
      - 80:80
    volumes:
      - ./frontend/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - photo_storage:/app/photo
    restart: always

volumes:
  vehicle_db:
  photo_storage: