services:
  backend:
    build: .
    command: sh -c "alembic upgrade head && python seed_db.py && python main.py"
    ports:
      - 8000:8000
    volumes:
      - ./src/vehicle/:/app/src/vehicle/
    env_file:
      - .env
    depends_on:
      db:
       condition: service_healthy
    restart: on-failure

  
  db:
    image: postgres:16
    restart: always
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}"]
      interval: 1s
      timeout: 5s
      retries: 10
    env_file:
      - .env
    volumes:
      - vehicle_db:/var/lib/postgres/data

volumes:
  vehicle_db: