services:
  backend:
    build: .
    command: sh -c "alembic upgrade head && python main.py"
    ports:
      - 8000:8000
    volumes:
      - ./src/vehicle/:/app/src/vehicle/
    env_file:
      - .env
    depends_on:
      - db
  
  db:
    image: postgres:16
    restart: always
    env_file:
      - .env
    volumes:
      - vehicle_db:/var/lib/postgres/data

volumes:
  vehicle_db: