"""add enum

Revision ID: 094bee9f6cb0
Revises: f18c8c4998d6
Create Date: 2025-05-17 11:31:21.891161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '094bee9f6cb0'
down_revision: Union[str, None] = 'f18c8c4998d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE maintenancecategory AS ENUM "
               "('ENGINE', 'TRANSMISSION', 'SUSPENSION', 'BRAKES', "
               "'STEERING', 'ELECTRICAL', 'FUEL_SYSTEM', 'EXHAUST', "
               "'CLIMATE', 'BODY', 'OTHER')")
    op.alter_column('maintenances', 'probeg',
                   new_column_name='mileage',
                   existing_type=sa.Numeric(precision=8, scale=0),
                   existing_nullable=False)
    op.execute("""
        ALTER TABLE maintenances 
        ALTER COLUMN category_of_work 
        TYPE maintenancecategory 
        USING (
            CASE category_of_work
                WHEN 'Двигатель и его компоненты' THEN 'ENGINE'::maintenancecategory
                WHEN 'Трансмиссия' THEN 'TRANSMISSION'::maintenancecategory
                WHEN 'Подвеска и ходовая часть' THEN 'SUSPENSION'::maintenancecategory
                WHEN 'Тормозная система' THEN 'BRAKES'::maintenancecategory
                WHEN 'Рулевое управление' THEN 'STEERING'::maintenancecategory
                WHEN 'Электрооборудование' THEN 'ELECTRICAL'::maintenancecategory
                WHEN 'Топливная система' THEN 'FUEL_SYSTEM'::maintenancecategory
                WHEN 'Выхлопная система' THEN 'EXHAUST'::maintenancecategory
                WHEN 'Система кондиционирования' THEN 'CLIMATE'::maintenancecategory
                WHEN 'Кузовные работы' THEN 'BODY'::maintenancecategory
                ELSE 'OTHER'::maintenancecategory
            END
        )
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('maintenances', 'mileage',
                   new_column_name='probeg',
                   existing_type=sa.Numeric(precision=8, scale=0),
                   existing_nullable=False)
    op.execute("""
        ALTER TABLE maintenances 
        ALTER COLUMN category_of_work 
        TYPE VARCHAR(128) 
        USING (category_of_work::text)
    """)
    op.execute("DROP TYPE maintenancecategory")
    # ### end Alembic commands ###
