"""change year_of_release

Revision ID: b660ccbec063
Revises: f3cfab7af0c5
Create Date: 2025-04-24 19:50:38.550442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b660ccbec063'
down_revision: Union[str, None] = 'f3cfab7af0c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
    ALTER TABLE cars
    ALTER COLUMN year_of_release
    TYPE INTEGER
    USING EXTRACT(YEAR FROM year_of_release)::INTEGER
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
        ALTER TABLE cars
        ALTER COLUMN year_of_release
        TYPE DATE
        USING TO_DATE(year_of_release::TEXT, 'YYYY')
    """)
    # ### end Alembic commands ###
