"""add maintenances

Revision ID: f18c8c4998d6
Revises: b660ccbec063
Create Date: 2025-05-05 19:19:18.719668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f18c8c4998d6'
down_revision: Union[str, None] = 'b660ccbec063'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('maintenances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('car_vin', sa.String(length=17), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('probeg', sa.Numeric(precision=8, scale=0), nullable=False),
    sa.Column('cost', sa.Numeric(precision=8, scale=0), nullable=False),
    sa.Column('comments', sa.String(), nullable=True),
    sa.Column('category_of_work', sa.String(length=128), nullable=False),
    sa.Column('documents', postgresql.ARRAY(sa.String(length=512)), nullable=True),
    sa.ForeignKeyConstraint(['car_vin'], ['cars.vin'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('cars', 'year_of_release',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cars', 'year_of_release',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_table('maintenances')
    # ### end Alembic commands ###
